# Generated by Django 3.1.2 on 2020-12-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image_url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='identipaint_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='CardStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.ManyToManyField(to='identipaint_app.Artist')),
                ('study_paintings', models.ManyToManyField(related_name='study_paintings', to='identipaint_app.Painting')),
                ('test_paintings', models.ManyToManyField(related_name='test_paintings', to='identipaint_app.Painting')),
            ],
        ),
    ]
